Repository wecode-bootcamp-korea/41-1st-Dwae-Getarian-frontend, pull requests merged in 2023-01, with the labels that each got.

#9 [41기 권나현]ADD: payment box 레이아웃 추가
  src/pages/Main/Components/payment/Payment.jsx
  src/pages/Main/Components/payment/payment.scss
Labels: 멘토 리뷰 요청

#3 [41기 권나현]ADD: detail page 커밋
  src/Router.js
  src/components/Nav/Nav.jsx
  src/components/NotFound.jsx
  src/index.js
  src/pages/Main/Components/Product/Product.jsx
  src/pages/Main/Components/Product/components/ProductDetail/ProductDetail.jsx
  src/pages/Main/Components/Product/components/ProductDetail/ProductDetail.scss
  src/pages/Main/Components/Product/components/ProductDetail/productDetailBottom/ProductDetailBottom.jsx
  src/pages/Main/Components/Product/components/ProductDetail/productDetailBottom/ProductDetailBottom.scss
Labels: Conflict 해결 요청, 멘토 리뷰 요청

#11 [41기 조윤환]ADD:footer레이아웃
  src/Router.js
  src/pages/Main/Components/Footer/Footer.jsx
  src/pages/Main/Components/Footer/Footer.scss
Labels: Conflict 해결 요청, 멘토 리뷰 요청

#8 [41기 권나현]ADD: product page 커밋
  src/App.js
  src/Router.js
  src/components/Nav/Nav.jsx
  src/components/NotFound.jsx
  src/pages/Main/Components/Product/components/BestProduct/BestProduct.jsx
  src/pages/Main/Components/Product/components/BestProduct/BestProduct.scss
  src/pages/Main/Components/Product/components/ProductCompo/ProductCompo.jsx
  src/pages/Main/Components/Product/components/ProductCompo/ProductCompo.scss
  src/pages/Main/Components/Product/components/ProductFood/ProductFood.jsx
  src/pages/Main/Components/Product/components/ProductFood/ProductFood.scss
  src/pages/Main/Components/Product/components/ProductList/PoductListItem/ProductListItem.jsx
  src/pages/Main/Components/Product/components/ProductList/PoductListItem/ProductListItem.scss
  src/pages/Main/Components/Product/components/ProductList/ProductList.jsx
  src/pages/Main/Components/Product/components/ProductList/ProductList.scss
  src/pages/Main/Components/Product/components/ProductMealKit/ProductMeaKit.jsx
  src/pages/Main/Components/Product/components/ProductMealKit/ProductMeaKit.scss
  src/pages/Main/Components/Product/components/ProductNav/ProductNav.jsx
  src/pages/Main/Components/Product/components/ProductNav/ProductNav.scss
Labels: 멘토 리뷰 요청

#10 [41기 권나현]ADD: cart 페이지 레이아웃 추가
  src/pages/Cart/Cart.jsx
  src/pages/Cart/Cart.scss
  src/pages/Cart/CartList/CartList.jsx
  src/pages/Cart/CartList/cartList.scss
  src/pages/Main/Components/Cart/Cart.jsx
  src/pages/Main/Components/Cart/Cart.scss
Labels: 멘토 리뷰 요청, 수정 요청

#13 [41기 권나현]Modify: 총 합계 구현(기능)
  src/pages/Main/Components/Product/components/ProductDetail/ProductDetail.jsx
Labels: 멘토 리뷰 요청, 수정 요청

#20 public폴더에 mock데이터 2개 추가, productFood페이지에 useEffect를 활용하여 fetch, produ…
  public/data/mock.json
  public/data/mock2.json
  src/pages/Main/Components/Product/ProductList/ProductList.jsx
  src/pages/Main/Components/Product/components/ProductCompo/ProductCompo.jsx
  src/pages/Main/Components/Product/components/ProductFood/ProductFood.jsx
  src/pages/Main/Components/Product/components/ProductList/PoductListItem/ProductListItem.jsx
  src/pages/Main/Components/Product/components/ProductList/PoductListItem/ProductListItem.scss
  src/pages/Main/Components/Product/components/ProductList/PoductListItem/productListImg/ProductListImg.jsx
  src/pages/Main/Components/Product/components/ProductList/PoductListItem/productListImg/ProductListImg.scss
  src/pages/Main/Components/Product/components/ProductList/ProductList.jsx
  src/pages/Main/Components/Product/components/ProductList/ProductList.scss
  src/pages/Main/Components/Product/components/ProductMealKit/ProductMeaKit.jsx
  src/pages/Main/Components/Product/components/ProductNav/ProductNav.jsx
  src/pages/Main/Components/Product/components/ProductNav/ProductNav.scss
Labels: 멘토 리뷰 요청

#5 [41기 조윤환]ADD:결제페이지 레이아웃 구현중
  pull_request_template.md
  src/Router.js
  src/components/NotFound.jsx
  src/pages/Main/Components/Order/Order.jsx
  src/pages/Main/Components/Order/Order.scss
  src/pages/Main/Components/Product/Product.jsx
Labels: 멘토 리뷰 요청

#7 [41기 김진우] Nav 구현
  src/Router.js
  src/components/Nav/Nav.jsx
  src/components/Nav/Nav.scss
  src/pages/Main/Components/Product/Product/Product.jsx
  src/pages/Main/Components/Product/Product/Product.scss
  src/pages/Main/Components/Recipe/Recipe.jsx
  src/pages/Main/Components/Recipe/Recipe.scss
  src/styles/common.scss
Labels: 멘토 리뷰 요청, 완료

#18 [41기 조윤환]modify:footer 위치조정했습니다
  src/Router.js
  src/components/Footer/Footer.jsx
  src/components/Footer/Footer.scss
  src/pages/Main/Components/Footer/Footer.jsx
  src/pages/Main/Components/Footer/Footer.scss
  src/pages/Main/Components/Product/components/ProductList/PoductListItem/productListImg/ProductListImg.jsx
Labels: 완료

#4 [41기 조윤환]ADD:메인페이지 레이아웃
  public/images/choyunhwan/flower.tiff
  public/images/choyunhwan/hi.tiff
  public/images/choyunhwan/photo-1504204267155-aaad8e81290d.avif
  public/images/choyunhwan/photo-1510172951991-856a654063f9.avif
  public/images/choyunhwan/photo-1553447974-62ec8ac208b6.avif
  public/images/edgar-castrejon-J04BD4ysoh8-unsplash.jpg
  src/Router.js
  src/pages/Main/Components/Brand/Brand.jsx
  src/pages/Main/Components/Maincomponents/MainEvent/MainEvent.jsx
  src/pages/Main/Components/Maincomponents/MainEvent/MainEvent.scss
  src/pages/Main/Components/Maincomponents/MainEvent/Timer.js
  src/pages/Main/Components/Maincomponents/Mainbest/Best.scss
  src/pages/Main/Components/Maincomponents/Mainbest/BestItem.jsx
  src/pages/Main/Components/Maincomponents/Mainbest/BestMenu.jsx
  src/pages/Main/Components/Maincomponents/Mainbest/BestSlide.jsx
  src/pages/Main/Components/Maincomponents/Mainbest/BestSlide.scss
  src/pages/Main/Components/Maincomponents/Notice/Notice.js
  src/pages/Main/Components/Maincomponents/Notice/Notice.scss
  src/pages/Main/Components/Maincomponents/Recipe/Recipe.jsx
  src/pages/Main/Components/Maincomponents/Recipe/Recipe.scss
  src/pages/Main/Components/Maincomponents/Slidecomponent/Slide.jsx
  src/pages/Main/Components/Maincomponents/Slidecomponent/Slide.scss
  src/pages/Main/Components/Maincomponents/Slidecomponent/SlideData.js
  src/pages/Main/Components/Order/Order.jsx
  src/pages/Main/Components/Order/Order.scss
  src/pages/Main/Main.jsx
  src/pages/Main/Main.scss
  src/pages/SignUp/SignUp.scss
Labels: 멘토 리뷰 요청

#16 [41기 김진우] 마이페이지 구현
  public/data/mypageProductData.json
  public/data/mypageUserData.json
  public/data/recipeProductData.json
  src/App.js
  src/Router.js
  src/components/Nav/Nav.jsx
  src/index.js
  src/pages/Login/My/My.jsx
  src/pages/Login/My/My.scss
  src/pages/Login/My/MyProducts.jsx
  src/styles/variables.scss
Labels: 멘토 리뷰 요청, 수정 요청

#25 [41기 권나현]매개변수를 받아와서 cart item 총 합계 구현
  src/pages/Main/Components/payment/Payment.jsx
  src/pages/Main/Components/payment/payment.scss
Labels: 멘토 리뷰 요청

#17 [41기 정다경] MODIFY : 수정요청 수정
  src/Router.js
  src/pages/MySubPage/Benefits/Benefits.jsx
  src/pages/MySubPage/Benefits/Benefits.scss
Labels: 멘토 리뷰 요청

#23 [41기 권나현]productCompo fetch수정, 필요없는 변수들 제거
  src/pages/Main/Components/Product/components/ProductCompo/ProductCompo.jsx
  src/pages/Main/Components/Product/components/ProductCompo/ProductCompo.scss
  src/pages/Main/Components/Product/components/ProductFood/ProductFood.jsx
  src/pages/Main/Components/Product/components/ProductList/ProductList.jsx
  src/pages/Main/Components/Product/components/ProductListItem/PoductListItem/ProductListItem.jsx
  src/pages/Main/Components/Product/components/ProductListItem/PoductListItem/ProductListItem.scss
  src/pages/Main/Components/Product/components/ProductListItem/PoductListItem/productListImg/ProductListImg.jsx
  src/pages/Main/Components/Product/components/ProductListItem/PoductListItem/productListImg/ProductListImg.scss
  src/pages/Main/Components/Product/components/ProductMealKit/ProductMeaKit.jsx
  src/pages/Main/Components/Product/components/ProductNav/ProductNav.jsx
  src/pages/Main/Components/Product/components/ProductNav/ProductNav.scss
Labels: 멘토 리뷰 요청

#26 [41기 정다경] activityList UI 및 Nav 추가
  src/pages/Login/My/ActivityList/ActivityList.jsx
  src/pages/Login/My/ActivityList/ActivityList.scss
Labels: 멘토 리뷰 요청

#29 [41기 김진우] 레시피 페이지 페이지네이션 구현
  src/pages/Main/Components/Recipe/ImageSlider.js
  src/pages/Main/Components/Recipe/Recipe.jsx
  src/pages/Main/Components/Recipe/Recipe.scss
  src/pages/Main/Components/Recipe/RecipePresent.jsx
  src/pages/Main/Components/Recipe/RecipePresent.scss
  src/pages/Main/Components/Recipe/RecipeTeaWear.jsx
Labels: 멘토 리뷰 요청

#19 [41기 권나현]ADD: index.js수정, Router.js수정, Nav.js수정 variable.scss 수정
  src/Router.js
  src/index.js
  src/styles/common.scss
  src/styles/variables.scss
Labels: 멘토 리뷰 요청

#28 [41기 조윤환]ADD:메인페이지에서링크연결
  public/images/brand.jpg
  public/images/choyunhwan/ella-olsson-lMcRyBx4G50-unsplash.jpg
  public/images/choyunhwan/three.avif
  public/images/choyunhwan/two.jpg
  public/images/mypage.jpg
  src/pages/Main/Components/Maincomponents/MainEvent/MainEvent.jsx
  src/pages/Main/Components/Maincomponents/MainEvent/MainEvent.scss
  src/pages/Main/Components/Maincomponents/Mainbest/Best.scss
  src/pages/Main/Components/Maincomponents/Mainbest/BestItem.jsx
  src/pages/Main/Components/Maincomponents/Mainbest/BestItem.scss
  src/pages/Main/Components/Maincomponents/Mainbest/BestMenu.jsx
  src/pages/Main/Components/Maincomponents/Notice/Notice.js
  src/pages/Main/Components/Maincomponents/Notice/Notice.scss
  src/pages/Main/Components/Maincomponents/Recipe/Recipe.jsx
  src/pages/Main/Components/Maincomponents/Recipe/Recipe.scss
  src/pages/Main/Components/Maincomponents/Slidecomponent/Slide.jsx
  src/pages/Main/Components/Maincomponents/Slidecomponent/Slide.scss
  src/pages/Main/Components/Maincomponents/Slidecomponent/SlideData.js
  src/pages/Main/Main.jsx
  src/pages/Main/Main.scss
Labels: 멘토 리뷰 요청

#31 [41기 김진우] 라우터 경로 수정
  src/Router.js
  src/components/Nav/Nav.jsx
  src/components/Nav/Nav.scss
  src/pages/Main/Components/Cart/Cart.jsx
  src/pages/Main/Components/Cart/Cart.scss
  src/pages/Main/Components/Cart/CartList/CartList.jsx
  src/pages/Main/Components/Cart/CartList/cartList.scss
  src/pages/Main/Components/Product/components/ProductCompo/ProductCompo.jsx
  src/pages/Main/Components/Product/components/ProductDetail/ProductDetail.jsx
  src/pages/Main/Components/Product/components/ProductDetail/ProductDetail.scss
  src/pages/Main/Components/Recipe/Recipe.jsx
  src/pages/Main/Components/Recipe/RecipePresent.jsx
Labels: 멘토 리뷰 요청

#14 [41기 정다경] ADD : disabled를 이용한 login 구현
  public/images/checked.png
  src/Router.js
  src/pages/Login/Login.jsx
  src/pages/Login/Login.scss
  src/pages/Logout/Logout.jsx
  src/pages/Logout/Logout.scss
  src/pages/SignUp/SignUp.scss
Labels: 멘토 리뷰 요청

#22 [41기 조윤환] Feature/order 결제페이지
  src/Router.js
  src/pages/Main/Components/Order/Order.jsx
  src/pages/Main/Components/Order/Order.scss
  src/pages/Main/Components/Order/OrderItems.scss
  src/pages/Main/Components/Order/OrderedItems.jsx
  src/pages/Main/Components/payment/OrderPayment.jsx
  src/pages/Main/Components/payment/OrderPayment.scss
Labels: 멘토 리뷰 요청

#33 [41기 권나현]Modify 이미지수정, 파비콘 추가
  public/favicon.ico
  public/index.html
  src/pages/Main/Components/Product/components/ProductCompo/ProductCompo.scss
  src/pages/Main/Components/Product/components/ProductMealKit/ProductMeaKit.jsx
Labels: 멘토 리뷰 요청

#32 [41기 조윤환]modify:링크 경로 수정
  src/components/Footer/Footer.jsx
Labels: 멘토 리뷰 요청

#27 [41기 정다경] orderReservation conflict router 수정
  package-lock.json
  public/data/my_reservation.json
  src/Router.js
  src/pages/MySubPage/MyReservation/MyOhDelivery.jsx
  src/pages/MySubPage/MyReservation/MyOhDelivery.scss
  src/pages/MySubPage/MyReservation/MyReservation.jsx
  src/pages/MySubPage/MyReservation/MyReservation.scss
Labels: 멘토 리뷰 요청

#30 [41기 정다경] modifySignup router 수정
  src/Router.js
  src/pages/SignUp/SignUp.jsx
  src/pages/SignUp/SignUp.scss
Labels: 멘토 리뷰 요청

#36 [41기 권나현]Modify: cart fetch수정, search파일 추가, nav에 cartIcon에 이벤트 추가, search파일에 f…
  src/Router.js
  src/components/Nav/Nav.jsx
  src/components/Nav/Nav.scss
  src/pages/Main/Components/Cart/Cart.jsx
  src/pages/Main/Components/Cart/Cart.scss
  src/pages/Main/Components/Cart/CartList/CartList.jsx
  src/pages/Main/Components/Product/components/ProductCompo/ProductCompo.jsx
  src/pages/Main/Components/Product/components/ProductCompo/ProductCompo.scss
  src/pages/Main/Components/Product/components/ProductDetail/ProductDetail.jsx
  src/pages/Main/Components/Product/components/ProductMealKit/ProductMeaKit.jsx
  src/pages/Main/Components/payment/Payment.jsx
  src/pages/Main/Components/payment/payment.scss
  src/pages/Main/Components/search/Search.jsx
  src/pages/Main/Components/search/search.scss
  src/pages/Main/Components/search/searchList/SearchList.jsx
  src/pages/Main/Components/search/searchList/searchItem/SearchItem.jsx
  src/pages/Main/Components/search/searchList/searchItem/searchItem.scss
  src/pages/Main/Components/search/searchList/searchList.scss
Labels: 멘토 리뷰 요청

#37 [41기 정다경] MODIFY : Benefits.scss 수정
  src/pages/MySubPage/Benefits/Benefits.scss
Labels: 멘토 리뷰 요청

#38 [41기 정다경] modifyActivityList.scss 수정
  src/pages/Login/My/ActivityList/ActivityList.scss
Labels: 멘토 리뷰 요청

#39 [41기 정다경] MODIFY : router 수정
  src/Router.js
Labels: 멘토 리뷰 요청

#40 [41기 정다경] feature/modifyRouter1 router 수정
  src/Router.js
Labels: 멘토 리뷰 요청

#41 레이아웃수정
  src/pages/Main/Components/Maincomponents/Slidecomponent/Slide.scss
Labels: 멘토 리뷰 요청

#34 [41기 김진우] Modify: 페이지네이션 버튼 css 수정
  src/Router.js
  src/components/Nav/Nav.jsx
  src/components/Nav/Nav.scss
  src/pages/Login/My/ActivityList/ActivityList.jsx
  src/pages/Login/My/My.jsx
  src/pages/Main/Components/Cart/Cart.jsx
  src/pages/Main/Components/Order/Order.jsx
  src/pages/Main/Components/Product/components/ProductDetail/ProductDetail.jsx
  src/pages/Main/Components/Product/components/ProductFood/ProductFood.jsx
  src/pages/Main/Components/Product/components/ProductMealKit/ProductMeaKit.jsx
  src/pages/Main/Components/Recipe/RecipePresent.scss
  src/pages/MySubPage/Benefits/Benefits.jsx
  src/pages/MySubPage/MyReservation/MyReservation.jsx
Labels: 멘토 리뷰 요청

#35 Modify:결제창 기능구현중
  src/Router.js
  src/pages/Main/Components/Order/Order.jsx
  src/pages/Main/Components/Order/Order.scss
  src/pages/Main/Components/Order/OrderItems.scss
  src/pages/Main/Components/Order/OrderedItems.jsx
  src/pages/Main/Components/payment/OrderPayment.jsx
Labels: Conflict 해결 요청, 추가 기능 구현 중
